// announcements-data.js
// Base announcement data — loaded by admin.html and announcements.html

window.BHSS_ANNOUNCEMENTS = [
  {
    id: "bhss-elections-campaign-materials",
    title: "BHSS Elections Campaign Materials",
    category: "Elections",
    author: "BHSS McMaster",
    date: "2026-03-28",
    readTime: 1,
    excerpt: "Hey HHSP! Get excited because the voting period for the 2026/27 BHSS Spring General Election is now open. Find all campaign materials, candidate profiles, and voting information here.",
    body: "Hey HHSP! Get excited because the voting period for the 2026/27 BHSS Spring General Election is now open. The voting period will run from March 27 at 9:00 AM to March 31 at 9:00 AM. To cast your vote, please refer to the email you will receive from the MSU voting system. Campaign materials from all candidates are linked below. If you have any questions, feel free to reach out to bhssele@mcmaster.ca.",
    image: "assets/images/banners/log_banner@4x.png",
    views: 11,
    pinned: true
  },
  {
    id: "Welcome-to-the-new-bhss-website",
    title: "Welcome to the new BHSS website!",
    category: "General",
    author: "BHSS McMaster",
    date: "2026-03-28",
    readTime: 2,
    excerpt: "The BHSS website has been completely redesigned to offer a smoother, more user-friendly experience for all Health Sci students.",
    body: "The BHSS website has been completely redesigned to offer a smoother, more user-friendly experience for all Health Sci students. We're in the process of gathering everything Health Sci and putting it in one place. Over time, this resource will slowly grow and house all things Health Sci, for us, by us. If you notice any issues or have suggestions, please reach out to bhsscom@mcmaster.ca.",
    image: "assets/images/banners/com_banner@4x.png",
    views: 1,
    pinned: false
  },
  {
    id: "biannual-formal-bylaw-vote",
    title: "Biannual Formal Bylaw Vote",
    category: "Social",
    author: "BHSS McMaster",
    date: "2026-03-28",
    readTime: 1,
    excerpt: "BHSS Socials is proposing a shift to a biannual formal model, meaning formals would typically take place every other year.",
    body: "BHSS Socials is proposing a shift to a biannual formal model, meaning formals would typically take place every other year (e.g., 2026, 2028, 2030), with flexibility to host events in off-years if desired. This proposal comes in response to declining attendance over the past three years, along with increasing financial pressure to run the event annually. Please read the full proposal before voting. Voting closes March 31, 2026. https://forms.gle/yu29fZcVi7ccuG2f9. If you have any questions or additional comments, feel free to reach out to us at bhsssoc@mcmaster.ca.",
    image: "assets/images/banners/soc_banner@4x.png",
    views: 3,
    pinned: false
  },
  {
    id: "catalyst-funding-deadline",
    title: "Last Call for Catalyst Funding",
    category: "Finance",
    author: "BHSS McMaster",
    date: "2026-03-25",
    readTime: 1,
    excerpt: "The clock is ticking for the final round of Catalyst funding applications of the year. Deadline: March 31st, 2026.",
    body: "The clock is ticking for the final round of Catalyst funding applications of the year! Don't miss your last chance to secure the resources your group needs. If you feel that there are spaces, communities, issues etc. that are underrepresented in our HHSP community, click the link in our bio to share your feedback and ideas! This could be something that would enhance an existing space or community, or could be a completely new initiative. With support from the BHSS Community Catalyst Fund you can bring your idea to life! Deadline: March 31st, 2026.",
    image: "assets/images/banners/fin_banner@4x.png",
    views: 8,
    pinned: false
  },
  {
    id: "edi-culture-day",
    title: "BHSS EDI Culture Day",
    category: "General",
    author: "BHSS McMaster",
    date: "2026-03-20",
    readTime: 1,
    excerpt: "BHSS EDI is hosting our first ever culture day! Attendees are encouraged to bring their cultural foods, clothes, or collaborate on a trifold.",
    body: "BHSS EDI is hosting our first ever culture day! Attendees are encouraged to bring their cultural foods, clothes, or collaborate with other peers on a trifold to represent their cultural background(s). Find more information and RSVP at the link in our bio.",
    image: "assets/images/banners/com_banner@4x.png",
    views: 5,
    pinned: false
  },
  {
    id: "spring-elections-voting-open",
    title: "Spring 2026 Elections Voting Now Open",
    category: "Elections",
    author: "BHSS McMaster",
    date: "2026-03-27",
    readTime: 1,
    excerpt: "Voting is now open for the BHSS Spring 2026 Elections. The voting period runs March 27–31 at 9:00 AM.",
    body: "Hey HHSP! Voting is now open for the BHSS Spring 2026 Elections. The voting period will run from March 27 at 9:00 AM to March 31 at 9:00 AM. To cast your vote, please refer to the email you will receive from the MSU voting system. If you have any questions, feel free to reach out!",
    image: "assets/images/banners/log_banner@4x.png",
    views: 14,
    pinned: false
  },
  {
    id: "hot-breakfast-march",
    title: "Hot Breakfast Alert — Pancakes & Turkey Bacon!",
    category: "Finance",
    author: "BHSS McMaster",
    date: "2026-03-24",
    readTime: 1,
    excerpt: "Come to the Health Sci Lounge this Wednesday for pancakes and turkey bacon! Wednesday, March 25th | 10am–12pm.",
    body: "Come to the Health Sci Lounge this Wednesday for pancakes and turkey bacon! Wednesday, March 25th | 10am–12pm | Health Science Lounge. The setup: Take up to 2 items. Weekly staples: fruit, cereal, granola bars, tea, hot chocolate. March specialty: Turkey bacon and pancakes!",
    image: "assets/images/banners/fin_banner@4x.png",
    views: 22,
    pinned: false
  },
  {
    id: "nominations-open-spring-election",
    title: "Nomination Forms Now Open — Spring General Election",
    category: "Elections",
    author: "BHSS McMaster",
    date: "2026-03-10",
    readTime: 2,
    excerpt: "Nomination forms for the 2026-2027 Spring General Election are now open. Submit by March 18th at 5 PM EST.",
    body: "Nomination forms for the 2026-2027 Spring General Election are now OPEN. If you are interested in this great opportunity to advocate for HHSP and showcase our diverse student body, please complete the nomination form linked in our bio and send a PDF to the Election Coordinators (bhssele@mcmaster.ca) by March 18th at 5 PM. There will be no exceptions. As part of the nomination process, we now require completion of a quiz to ensure candidates are well-informed about the election process.",
    image: "assets/images/banners/log_banner@4x.png",
    views: 19,
    pinned: false
  },
  {
    id: "brain-bites-midterm-season",
    title: "BHSS Brain Bites — Free Snacks Every Thursday",
    category: "Finance",
    author: "BHSS McMaster",
    date: "2026-03-12",
    readTime: 1,
    excerpt: "Free snacks every Thursday 1:30–4:00 PM for midterm season. Goldfish, juice, chocolates, ramen, and more!",
    body: "Studying nonstop? Don't forget to pause. We're hosting BHSS Brain Bites for students during midterm season. Stop by, take a break, and recharge! We've got Goldfish, Juice, Brookside Chocolates, Protein Granola Bars, Seaweed, Buldak Ramen, and MORE! 1:30pm–4:00pm every Thursday until the end of the semester!",
    image: "assets/images/banners/fin_banner@4x.png",
    views: 31,
    pinned: false
  },
  {
    id: "discount-card-launch",
    title: "BHSS Discount Card is Here!",
    category: "Finance",
    author: "BHSS McMaster",
    date: "2026-03-05",
    readTime: 1,
    excerpt: "Our BHSS Discount Card gives students access to exclusive savings at participating local businesses.",
    body: "Our BHSS Discount Card gives students access to exclusive savings at participating local businesses. It's our way of supporting the community while helping students save on food, game cafes, and more! Cards are available at the BHSS Office and BHSS Breakfast. Make sure to grab your card and start saving!",
    image: "assets/images/banners/fin_banner@4x.png",
    views: 17,
    pinned: false
  },
  {
    id: "casino-night",
    title: "BHSS Finance presents Casino Night!",
    category: "Finance",
    author: "BHSS McMaster",
    date: "2026-03-01",
    readTime: 1,
    excerpt: "Join us for an evening of Poker, Craps, Blackjack, board games, a human slot machine, magic show, and more!",
    body: "Feeling down after the Anat Midterm and want to have some fun? BHSS Finance presents Casino Night! Join us for a fun evening of Poker, Craps, Blackjack, board games, a human slot machine, magic show, and MORE! Buy chips to play and redeem them at the end of the night for a chance to win BHSS merch (tote bags, water bottles, and hats), gift cards and other prizes!",
    image: "assets/images/banners/fin_banner@4x.png",
    views: 9,
    pinned: false
  },
  {
    id: "academics-bootcamp",
    title: "BHSS Academics Bootcamp — Sign Up Now",
    category: "Academics",
    author: "BHSS McMaster",
    date: "2026-02-28",
    readTime: 2,
    excerpt: "Prepare for exam season with the BHSS Academics Bootcamp. Study sessions, peer tutoring, and resource guides available.",
    body: "Prepare for exam season with the BHSS Academics Bootcamp. We have organized study sessions, peer tutoring, and comprehensive resource guides to help you succeed. Check out the BHSS Academics Google Drive for all resources. Sign up via the link in our bio. Good luck with your studies!",
    image: "assets/images/banners/aca_banner@4x.png",
    views: 43,
    pinned: false
  }
];
